global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alert.rules"
  # "another_file_with_alerts"

scrape_configs:
  - job_name: "local"
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'httpd'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://httpd:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'nginx'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://nginx:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'app'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['app:80']
    #  - targets: ['app:443']
    # scheme: https
    # tls_config:
      # ca_file: /etc/ssl/certs/prometheus-ca.crt
      # cert_file: /etc/ssl/certs/prometheus.crt
      # /etc/prometheus/prometheus.key

# Flask example app

  - job_name: 'flask'
    scrape_interval: 5s
    static_configs:
      - targets: ['flask-prometheus-example:8000'] 
